<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EquipoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('Equipos')->insert([
            [
                'Equipo'=>'1',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'2',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'3',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'4',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'5',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'6',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'7',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'8',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'9',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'10',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'11',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'12',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'13',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'14',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'15',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'16',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'17',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'18',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'19',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'20',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'21',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'22',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'23',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'24',
                'Aula'=>'A',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'1',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'2',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'3',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'4',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'5',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'6',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'7',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'8',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'9',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'10',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'11',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'12',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'13',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'14',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'15',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'16',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'17',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'18',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'19',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'20',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'21',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'22',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'23',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'24',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'25',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'26',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'27',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'28',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'29',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'30',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'31',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ],
            [
                'Equipo'=>'32',
                'Aula'=>'B',
                'Estado'=>'Disponible',
                'created_at' => date('y-m-d H:i:s'),
                'updated_at' => date('y-m-d H:i:s'),
            ]
            
        ]);
    }
}
